apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tasky.fullname" . }}
  labels:
    {{- include "tasky.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tasky.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tasky.selectorLabels" . | nindent 8 }}
    spec:
      # imagePullSecrets:
      #   - name: acr-secret
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SECRET_KEY
              value: {{ .Values.env.SECRET_KEY | quote }}
            - name: MONGODB_URI
              value: {{ .Values.env.MONGODB_URI | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
