# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Publish a Docker image

on:
  pull_request:
    branches:
      - main
  push:
    branches: ['main']

env:
  REGISTRY: demowiz.azurecr.io
  IMAGE_NAME: ${{ github.repository }}
  ACR_NAME: demowiz

permissions:
  id-token: write
  contents: read
  pull-requests: write 

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name ${{ env.ACR_NAME }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}
          flavor: |
            latest=true
      
      - name: Build  Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
          format: "table"
          exit-code: 1  # Fail workflow if vulnerabilities are found
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true  # Only fail for fixable issues
        continue-on-error: true  # Prevents workflow from stopping immediately

      - name: Save Trivy scan report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt
      
      - name: Push Docker image to ACR 
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      # - name: Log in to Azure Container Registry (ACR)
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.ACR_NAME }}.azurecr.io
      #     username: 00000000-0000-0000-0000-000000000000  # Not needed for OIDC but required by action
      #     password: unused  # Not needed for OIDC but required by action


      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #     flavor: |
      #       latest=true

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}