name: Trigger on folder changes

on:
  push:
    paths:
      - 'helm/**'  # Trigger only if files inside 'my-folder/' change
  pull_request:
    paths:
      - 'helm/**'  # Trigger on PRs that modify 'my-folder/'

env:
  ACR_NAME: wizdemoacr000897

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Azure login using Service Principal
          uses: azure/login@v2
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
  
        - name: Log in to Azure Container Registry (ACR) using Service Principal
          run: |
            az acr login --name ${{ env.ACR_NAME }} 
      
        - name: Set up Helm
          uses: azure/setup-helm@v1

        - name: Package Helm chart
          run: helm package ./helm

        - name: Push Helm chart to ACR
          run: |
            az acr helm push --name ${{ env.ACR_NAME }} ./helm/*.tgz