name: Trigger on folder changes

on:
  push:
    paths:
      - 'helm/**' 
      - '.github/workflows/helm-publish.yml'
  pull_request:
    paths:
      - 'helm/**'  
      - '.github/workflows/helm-publish.yml'

env:
  ACR_NAME: wizdemoacr000897
  ACR_REGISTRY: wizdemoacr000897.azurecr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure login using Service Principal
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Enable OCI Support in Helm
        run: |
          helm version
          helm plugin install https://github.com/chartmuseum/helm-push || true  # Ensure OCI plugin is installed
          echo "Enabling OCI support..."
          export HELM_EXPERIMENTAL_OCI=1  # Required for OCI support in Helm 3

      - name: Authenticate Helm with ACR
        run: |
          helm registry login ${{ env.ACR_REGISTRY }} \
            --username $(az acr credential show --name ${{ env.ACR_NAME }} --query "username" --output tsv) \
            --password $(az acr credential show --name ${{ env.ACR_NAME }} --query "passwords[0].value" --output tsv)

      - name: Package Helm chart
        run: helm package ./helm

      - name: Push Helm chart to ACR
        run: |
          export HELM_EXPERIMENTAL_OCI=1  # Ensure OCI support
          helm push *.tgz oci://${{ env.ACR_REGISTRY }}/helm
