name: Deploy Infrastructure

on:
  push:
    paths:
      - .image_tag

env:
  AWS_REGION: us-east-1
  #ECR_REPO: tasky
  #ACCOUNT_ID: 565393052020

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --name greg-wiz-cluster --region ${{ env.AWS_REGION }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Read image URL from file
      id: read_image
      run: |
        IMAGE=$(cut -d'#' -f1 < .image_tag | xargs)
        echo "IMAGE_URL=$IMAGE" >> $GITHUB_ENV

    - name: Deploy with Terraform
      working-directory: terraform
      run: |
        terraform init
        terraform apply -auto-approve \
          -var="mongo_uri=${{ secrets.MONGO_URI }}" \
          -var="secret_key=${{ secrets.SECRET_KEY }}" \
          -var="image_url=${{ env.IMAGE_URL }}"
